# Generated by Django 5.1.7 on 2025-04-11 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('is_income', models.BooleanField(default=False, verbose_name='Receita?')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('date', models.DateField(verbose_name='Data')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='financial.category', verbose_name='Categoria')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='accounts.entity', verbose_name='Entidade')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='accounts.paymentmethod', verbose_name='Forma de Pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(verbose_name='Número da parcela')),
                ('due_date', models.DateField(verbose_name='Data de vencimento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pago?')),
                ('fin_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='financial.financialrecord', verbose_name='Registro Financeiro')),
            ],
        ),
    ]
