# Generated by Django 6.0 on 2025-12-07 18:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='total amount')),
                ('purchase_date', models.DateField(verbose_name='purchase date')),
                ('number_of_installments', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='number of installments')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='core.category', verbose_name='category')),
                ('entity', models.ForeignKey(blank=True, help_text='Where the purchase was made', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='core.entity', verbose_name='entity')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='accounts.paymentmethod', verbose_name='payment method')),
            ],
            options={
                'verbose_name': 'purchase',
                'verbose_name_plural': 'purchases',
                'ordering': ['-purchase_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='installment number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='amount')),
                ('due_date', models.DateField(verbose_name='due date')),
                ('reference_month', models.PositiveSmallIntegerField(help_text='Month number (1-12)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='reference month')),
                ('reference_year', models.PositiveIntegerField(verbose_name='reference year')),
                ('paid', models.BooleanField(default=False, verbose_name='paid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='financial.purchase', verbose_name='purchase')),
            ],
            options={
                'verbose_name': 'installment',
                'verbose_name_plural': 'installments',
                'ordering': ['purchase', 'installment_number'],
            },
        ),
        migrations.CreateModel(
            name='Recurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='amount')),
                ('type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10, verbose_name='type')),
                ('frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom')], default='MONTHLY', max_length=10, verbose_name='frequency')),
                ('reference_day', models.PositiveSmallIntegerField(help_text='Day of month (1-31) or day of week (1-7)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='reference day')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for infinite recurrence', null=True, verbose_name='end date')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurrences', to='core.category', verbose_name='category')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurrences', to='core.entity', verbose_name='entity')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurrences', to='accounts.paymentmethod', verbose_name='payment method')),
            ],
            options={
                'verbose_name': 'recurrence',
                'verbose_name_plural': 'recurrences',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10, verbose_name='type')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='amount')),
                ('date', models.DateField(verbose_name='date')),
                ('confirmed', models.BooleanField(default=False, help_text='Whether the transaction has been confirmed', verbose_name='confirmed')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.category', verbose_name='category')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.entity', verbose_name='entity')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.paymentmethod', verbose_name='payment method')),
                ('purchase', models.ForeignKey(blank=True, help_text='If this is a statement payment linked to a purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='financial.purchase', verbose_name='purchase')),
                ('recurrence', models.ForeignKey(blank=True, help_text='If generated from a recurrence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='financial.recurrence', verbose_name='recurrence')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tag', verbose_name='tag')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.transaction', verbose_name='transaction')),
            ],
            options={
                'verbose_name': 'transaction tag',
                'verbose_name_plural': 'transaction tags',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='transactions', through='financial.TransactionTag', to='core.tag', verbose_name='tags'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['-purchase_date'], name='financial_p_purchas_d48b39_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['payment_method', '-purchase_date'], name='financial_p_payment_56ca1f_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['reference_year', 'reference_month'], name='financial_i_referen_94a899_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['due_date'], name='financial_i_due_dat_4d1420_idx'),
        ),
        migrations.AddIndex(
            model_name='installment',
            index=models.Index(fields=['paid'], name='financial_i_paid_e68cc5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='installment',
            unique_together={('purchase', 'installment_number')},
        ),
        migrations.AddIndex(
            model_name='recurrence',
            index=models.Index(fields=['active', 'frequency'], name='financial_r_active_5532d2_idx'),
        ),
        migrations.AddIndex(
            model_name='recurrence',
            index=models.Index(fields=['start_date', 'end_date'], name='financial_r_start_d_7c8ba8_idx'),
        ),
        migrations.AddIndex(
            model_name='transactiontag',
            index=models.Index(fields=['transaction', 'tag'], name='financial_t_transac_2345c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transactiontag',
            unique_together={('transaction', 'tag')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date', 'type'], name='financial_t_date_8d2b97_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['confirmed'], name='financial_t_confirm_a028aa_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-date', 'category'], name='financial_t_date_a81f49_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['-date', 'payment_method'], name='financial_t_date_b883f7_idx'),
        ),
    ]
