# Generated by Django 5.1.7 on 2025-04-14 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='financialrecord',
            options={'ordering': ['-date', '-amount'], 'verbose_name': 'Registro Financeiro', 'verbose_name_plural': 'Registros Financeiros'},
        ),
        migrations.AlterModelOptions(
            name='installment',
            options={'ordering': ['-due_date', 'installment_number'], 'verbose_name': 'Parcela', 'verbose_name_plural': 'Parcelas'},
        ),
    ]
