# Generated by Django 5.1.7 on 2025-04-24 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_entity_options_alter_paymentmethod_options_and_more'),
        ('financial', '0002_alter_category_options_alter_financialrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='accounts.entity', verbose_name='Entidade'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_records', to='accounts.paymentmethod', verbose_name='Forma de Pagamento'),
        ),
    ]
