# Generated by Django 5.1.7 on 2025-04-11 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('person_type', models.CharField(choices=[('F', 'Física'), ('J', 'Jurídica')], default='F', max_length=1, verbose_name='Tipo de Pessoa')),
                ('document', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF/CNPJ')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_institution', models.CharField(max_length=100, verbose_name='Instituição Financeira')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='accounts.entity', verbose_name='Proprietário')),
            ],
        ),
    ]
