# Generated by Django 6.0 on 2025-12-07 18:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Account name (e.g., "Nubank", "Bradesco CC")', max_length=100, verbose_name='name')),
                ('bank', models.CharField(max_length=100, verbose_name='bank')),
                ('type', models.CharField(choices=[('CHECKING', 'Checking Account'), ('SAVINGS', 'Savings Account'), ('INVESTMENT', 'Investment Account')], default='CHECKING', max_length=15, verbose_name='type')),
                ('color', models.CharField(blank=True, help_text='Hex color code (e.g., #FF5733)', max_length=7, verbose_name='color')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'bank account',
                'verbose_name_plural': 'bank accounts',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active'], name='accounts_ba_active_708f02_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Payment method name (e.g., "Nubank Credit Card")', max_length=100, verbose_name='name')),
                ('type', models.CharField(choices=[('PIX', 'PIX'), ('DEBIT', 'Debit Card'), ('CREDIT', 'Credit Card'), ('CASH', 'Cash'), ('TRANSFER', 'Bank Transfer'), ('BOLETO', 'Boleto')], max_length=10, verbose_name='type')),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Only for credit cards', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='credit limit')),
                ('closing_day', models.PositiveSmallIntegerField(blank=True, help_text='Day of month when the statement closes (1-31)', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='closing day')),
                ('due_day', models.PositiveSmallIntegerField(blank=True, help_text='Day of month when payment is due (1-31)', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='due day')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('bank_account', models.ForeignKey(blank=True, help_text='Associated bank account (for debit/PIX)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_methods', to='accounts.bankaccount', verbose_name='bank account')),
            ],
            options={
                'verbose_name': 'payment method',
                'verbose_name_plural': 'payment methods',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['active', 'type'], name='accounts_pa_active_6786cf_idx')],
            },
        ),
    ]
