# Generated by Django 5.1.7 on 2025-04-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': 'Entidade', 'verbose_name_plural': 'Entidades'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Forma de Pagamento', 'verbose_name_plural': 'Formas de Pagamento'},
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('C', 'Cartão'), ('B', 'Boleto'), ('D', 'Débito'), ('P', 'Pix'), ('T', 'Transferência'), ('O', 'Outros')], default='C', max_length=1, verbose_name='Tipo de Pagamento'),
        ),
    ]
